import re
import ssl
import socket
from urllib.parse import urlparse, urljoin
from collections import Counter

import requests

from core.engine import ReconModule, register_module
from core.utils import colored, random_ua


WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": [r"cf-ray", r"server:\s*cloudflare"],
        "body": [r"cloudflare"],
        "cookies": [r"__cfduid", r"cf_clearance", r"_cfuvid"],
    },
    "AWS WAF / CloudFront": {
        "headers": [r"x-amz-cf-id", r"x-amzn-", r"via:\s*cloudfront"],
        "body": [r"cloudfront", r"aws", r"Request blocked"],
        "cookies": [r"aws-waf-token", r"awselb"],
    },
    "Fortinet / FortiWeb": {
        "headers": [r"forti", r"server:\s*forti"],
        "body": [r"fortinet", r"fortiweb", r"fortigate"],
        "cookies": [],
    },
    "Imperva / Incapsula": {
        "headers": [r"x-iinfo", r"x-cdn:\s*incapsula"],
        "body": [r"incapsula", r"imperva", r"_Incapsula_Resource"],
        "cookies": [r"incap_ses", r"visid_incap"],
    },
    "Akamai": {
        "headers": [r"x-check-cacheable", r"akamai-", r"server:\s*akamai"],
        "body": [r"akamai"],
        "cookies": [],
    },
    "F5 BIG-IP": {
        "headers": [r"x-wa-info", r"server:\s*bigip", r"x-connection-info"],
        "body": [r"bigip", r"the request could not be fulfilled"],
        "cookies": [r"^ts[a-f0-9]{8}"],
    },
    "Sucuri": {
        "headers": [r"x-sucuri-id", r"x-sucuri-cache", r"server:\s*sucuri"],
        "body": [r"sucuri"],
        "cookies": [],
    },
    "ModSecurity": {
        "headers": [r"x-modsecurity", r"x-nws-log-id"],
        "body": [r"mod_security", r"modsecurity", r"naxsi", r"blocked by"],
        "cookies": [],
    },
    "Barracuda": {
        "headers": [r"server:\s*barracuda"],
        "body": [r"barracuda"],
        "cookies": [r"barra_counter_session"],
    },
    "Wordfence": {
        "headers": [],
        "body": [r"wordfence", r"generated by wordfence"],
        "cookies": [r"wfvt_"],
    },
    "StackPath": {
        "headers": [r"server:\s*stackpath"],
        "body": [r"stackpath"],
        "cookies": [],
    },
}

PROBES = [
    ("GET", "/"),
    ("GET", "/?test=<script>alert(1)</script>"),
    ("GET", "/?id=' OR '1'='1"),
    ("GET", "/?q=UNION SELECT * FROM users"),
    ("GET", "/.env"),
    ("GET", "/../../etc/passwd"),
    ("POST", "/"),
    ("HEAD", "/"),
]

THRESHOLD = 6


@register_module
class WAFHunterModule(ReconModule):
    name = "wafhunter"
    description = "Web Application Firewall detector with active probing and passive SSL analysis"

    def run(self, target):
        self.setup(target)

        parsed = urlparse(target)
        if not parsed.scheme:
            target = "https://" + target
            parsed = urlparse(target)
        base = f"{parsed.scheme}://{parsed.netloc}"
        host = parsed.netloc

        self.log(f"Detecting WAF for {base}")

        session = requests.Session()
        session.headers["User-Agent"] = random_ua()
        timeout = self.config.get("general", "timeout", default=8)

        def resolve_dns():
            try:
                addrs = socket.getaddrinfo(host, None)
                return sorted(set(a[4][0] for a in addrs))
            except Exception:
                return []

        def do_passive_ssl():
            info = {"dns": resolve_dns(), "cn": "", "san": []}
            try:
                ctx = ssl.create_default_context()
                with socket.create_connection((host, 443), timeout=4) as s:
                    with ctx.wrap_socket(s, server_hostname=host) as ss:
                        cert = ss.getpeercert()
                        for t in cert.get("subject", ()):
                            for k, v in t:
                                if k.lower() == "commonname":
                                    info["cn"] = v.lower()
                        for t in cert.get("subjectAltName", ()):
                            if t[0] == "DNS":
                                info["san"].append(t[1].lower())
            except Exception:
                pass
            return info

        def run_probes():
            results = []
            for method, path in PROBES:
                url = urljoin(base + "/", path.lstrip("/"))
                try:
                    if method == "GET":
                        resp = session.get(url, timeout=timeout, allow_redirects=False)
                    elif method == "HEAD":
                        resp = session.head(url, timeout=timeout, allow_redirects=False)
                    else:
                        resp = session.post(url, data={"test": "1"}, timeout=timeout, allow_redirects=False)
                    results.append({
                        "method": method,
                        "url": url,
                        "status": resp.status_code,
                        "headers": dict(resp.headers),
                        "body": resp.text[:2000],
                        "cookies": dict(resp.cookies),
                    })
                except Exception as e:
                    results.append({
                        "method": method,
                        "url": url,
                        "status": 0,
                        "headers": {},
                        "body": "",
                        "cookies": {},
                        "error": str(e),
                    })
            return results

        probes = run_probes()
        passive = do_passive_ssl()

        # Scoring — per probe, take max, not cumulative
        probe_scores = Counter()
        for probe in probes:
            h_text = " ".join(f"{k}:{v}" for k, v in probe["headers"].items()).lower()
            b_text = (probe["body"] or "").lower()
            c_text = " ".join(probe["cookies"].keys()).lower()
            st = probe["status"]

            for vendor, sig in WAF_SIGNATURES.items():
                pts = 0
                if any(re.search(p, h_text) for p in sig["headers"]):
                    pts += 5
                if any(re.search(p, b_text) for p in sig["body"]):
                    pts += 4
                if any(re.search(p, c_text) for p in sig["cookies"]):
                    pts += 3
                if st in (403, 406, 429, 501, 503):
                    pts += 3
                if pts > probe_scores[vendor]:
                    probe_scores[vendor] = pts

        # Passive SSL clues — weight reduced, only as tiebreaker
        combined = " ".join([passive.get("cn", "")] + passive.get("san", []))
        ssl_mapping = [
            ("cloudflare", "Cloudflare"),
            ("cloudfront", "AWS WAF / CloudFront"),
            ("forti", "Fortinet / FortiWeb"),
            ("incapsula", "Imperva / Incapsula"),
            ("imperva", "Imperva / Incapsula"),
            ("akamai", "Akamai"),
            ("bigip", "F5 BIG-IP"),
            ("sucuri", "Sucuri"),
            ("barracuda", "Barracuda"),
            ("modsecurity", "ModSecurity"),
        ]
        for keyword, vendor in ssl_mapping:
            if keyword in combined and probe_scores[vendor] >= 3:
                probe_scores[vendor] += 2

        # Normalize: count how many unique probes contributed evidence
        confirmed = Counter()
        for probe in probes:
            h_text = " ".join(f"{k}:{v}" for k, v in probe["headers"].items()).lower()
            b_text = (probe["body"] or "").lower()
            c_text = " ".join(probe["cookies"].keys()).lower()
            st = probe["status"]
            for vendor, sig in WAF_SIGNATURES.items():
                any_match = (
                    any(re.search(p, h_text) for p in sig["headers"]) or
                    any(re.search(p, b_text) for p in sig["body"]) or
                    any(re.search(p, c_text) for p in sig["cookies"]) or
                    (st in (403, 406, 429, 501, 503) and probe_scores[vendor] >= 3)
                )
                if any_match:
                    confirmed[vendor] += 1

        detected = []
        for vendor, score in probe_scores.items():
            confirm_count = confirmed.get(vendor, 0)
            if score >= THRESHOLD and confirm_count >= 2:
                confidence = min(100, int((score / 18.0) * 100))
                detected.append({
                    "vendor": vendor,
                    "score": score,
                    "probes_confirming": confirm_count,
                    "confidence": confidence,
                    "level": "HIGH" if confidence >= 80 else "MEDIUM" if confidence >= 50 else "LOW",
                })

        detected.sort(key=lambda x: x["score"], reverse=True)

        self.results["target"] = base
        self.results["host"] = host
        self.results["dns_ips"] = passive["dns"]
        self.results["probes"] = [
            {"method": p["method"], "url": p["url"], "status": p.get("status"), "error": p.get("error")}
            for p in probes
        ]
        self.results["waf_detected"] = detected
        self.results["ssl_info"] = {"cn": passive["cn"], "san": passive["san"]}

        print(f"\n{colored('='*60, 'red')}")
        print(f"{colored('WAF HUNTER SUMMARY', 'bold')}")
        print(f"{colored('='*60, 'red')}")
        print(f"  Target: {base}")
        print(f"  DNS:    {', '.join(passive['dns']) if passive['dns'] else 'Unknown'}")

        if detected:
            print(f"\n{colored('[!] WAF Detected:', 'red')}")
            for d in detected:
                print(f"  {colored('->', 'red')} {d['vendor']} (Score: {d['score']}, Confidence: {d['confidence']}% [{d['level']}])")
        else:
            print(f"\n{colored('[-] No WAF detected', 'green')}")

        print(f"\n  Probe results:")
        for p in probes:
            s = p.get("status", "ERR")
            s_colored = colored(str(s), "red") if s and s >= 400 else colored(str(s), "green")
            print(f"    [{p['method']}] {s_colored} {p['url']}")

        if passive["cn"]:
            print(f"\n  SSL CN:  {passive['cn']}")
        if passive["san"]:
            for san in passive['san']:
                print(f"  SSL SAN: {san}")

        session.close()
        self.teardown()
        return self.results
